---

- name: Install mysql packages
  apt:
    name:
    - mysql-server
    - python3-mysqldb
    state: present
  
- name: Create wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create wordpress  dabatase user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present
  no_log: True

- name: Start mysql service
  service: 
    name: mysql
    state: started
    enabled: yes